### ISSUE TITLE
Interface zum aussuchen der Daten erstellen

### ISSUE THREAD

**Issue by JosiasKasemann** [julius-gummersbach/cae-performance-data-monitoring-tool#10]
-Es muss ein passendes Programms für das Gui ausgesucht werden
-es soll eine Möglichkeit zum angeben eines Startzeitpunkts geben
-es soll sich ein oder zwei Threads angeben lassen, die angezeigt werden sollen
-es soll eine Operationion (+,-,....) auswählbar sein
-es soll möglich sein eine Dateart (errors, CPU auslastung...) auszuwählen
-ein Graph muss angezeigt werden( #8 )

**Comment by julius-gummersbach** [comment]
Continued in #8
