### ISSUE TITLE
Determine GUI-Framework

### ISSUE THREAD

**Issue by SuperNova2712** [julius-gummersbach/cae-performance-data-monitoring-tool#33]
We have to determine which framework to use.
Possible choices are:

- Qt 
  - GPLv3/GPLv2/LGPL
  - https://www.qt.io/
  - unsure if we can use it because of License
- wxWidgets  
  - no License 
  - https://wxwidgets.org/
  - quite old, but uses native SDKs
- CEGUI 
  - MIT-License
  - http://static.cegui.org.uk/docs/0.8.7/index.html 
  - newer Framework, made for games hence animations should work good
Would be nice if we could determine asap which framework to use.

**Comment by julius-gummersbach** [comment]
we are using a webpage instead
