### ISSUE TITLE
Graphoperation und Expression: Compatibility Check hinzufügen

### ISSUE THREAD

**Issue by julius-gummersbach** [julius-gummersbach/cae-performance-data-monitoring-tool#42]
Wenn zwei Graphen verknüpft werden muss überprüft werden, ob die Datenpunkte zeitlich übereinanderliegen, bevor sie verrechnet werden.  
Das könnte man zum Beispiel über `frequenz / iterations` machen.
Es ist noch zu klären, wo der check gemacht wird, wahrscheinlich in der GraphOperation und in der Expression?

**Comment by TomsCodingCode** [comment]
Due to changes in the data model all graphs are compatable and there is no need to check compatibility
