### ISSUE TITLE
Update server-script

### ISSUE THREAD

**Issue by SuperNova2712** [julius-gummersbach/cae-performance-data-monitoring-tool#67]
Update the server script to fit the new requirements

**Comment by sburk6** [comment]
Adjusted the script some more while bugfixing. Maybe some recognizable functions would be nice for the graphs instead of only random ones? Paul proposed sin and cos

**Comment by julius-gummersbach** [comment]
That is a good idea, at least for some. We could add a "sinus-thread" and a "gauss-curve-thread" or something
