### ISSUE TITLE
Design webpage to show data

### ISSUE THREAD

**Issue by JosiasKasemann** [julius-gummersbach/cae-performance-data-monitoring-tool#8]
Ausgewählte Daten sollen als Histogramm oder Graph angezeigt werden.
Datenübergabeformat muss noch definiert werden.

**Comment by julius-gummersbach** [comment]
Instead of using a GUI Framework in C++ we will use a Webpage to show the data

**Comment by julius-gummersbach** [comment]
![grafik](https://user-images.githubusercontent.com/97508212/216124219-55c657c0-38e5-41fc-8d90-7085472fe97c.png)
Current State
