### ISSUE TITLE
Remove / change text in SVG images

### ISSUE THREAD

**Issue by julius-gummersbach** [julius-gummersbach/cae-performance-data-monitoring-tool#85]
rn the text in the generated svgs looks something like this:
![grafik](https://user-images.githubusercontent.com/97508212/218757021-d4263b29-388e-4dfb-8f3d-41d9e4e52960.png)

I don't think that's really fitting. It should either be removed or changed to something more fitting.

**Comment by sburk6** [comment]
Are the Axis-Descriptions okay?
I agree with the rest. Theoretically we could use the thread id for the blue graph description. That would be the actual graph name as generated by server.py tough, so something like 'A231JL' instead of 'Thread1'.

**Comment by julius-gummersbach** [comment]
Axis descriptions are OK. Maybe something like "Time (ms)" ?
I don't really think we need the "graph description" at all. all the information are shown in the data tables on the website. One could only argue that the text is beneficial when you export the svg to use it somewhere else...
